---
- name: Check existing installation
  ansible.builtin.stat:
    path: '{{ certificates_path }}'
  register: installation_path

- name: Get kubeadm join token
  ansible.builtin.command:
    cmd: kubeadm token create
  register: join_token
  changed_when: join_token.rc !=0
  delegate_to: "{{ groups['kube_master_nodes'] | first }}"
  when: not installation_path.stat.exists

- name: Get Discovery token hash
  ansible.builtin.shell:
    cmd: |
      openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: discovery_token_hash
  delegate_to: "{{ groups['kube_master_nodes'] | first }}"
  when: not installation_path.stat.exists

- name: Join worker node to cluster
  ansible.builtin.command:
    cmd: 'kubeadm join {{ master_node }}:6443 --token {{ join_token.stdout }} --discovery-token-ca-cert-hash sha256:{{ discovery_token_hash.stdout }}'
    creates: '{{ certificates_path }}'
  register: output
  changed_when: output.rc !=0
  become: yes
  when: not installation_path.stat.exists
