---
- name: Download flannel manifest file
  ansible.builtin.get_url:
    url: https://github.com/flannel-io/flannel/releases/download/v0.23.0/kube-flannel.yml
    dest: '{{ network_manifest_path }}'
    validate_certs: no
    mode: u=rw,g=r,o=r
    force: true

- name: Update pod CIDR in manifest file
  ansible.builtin.lineinfile:
    path: '{{ network_manifest_path }}'
    line: '      "Network": "10.32.0.0/16",'
    regexp: '^\s*\"Network\":\s*\".*?\",\s*$'

- name: Deploy flannel network
  remote_user: ubuntu
  kubernetes.core.k8s:
    state: present
    src: '{{ network_manifest_path }}'
