---
# tasks file for master

- name: Intialise master
  ansible.builtin.command:
    cmd: 'kubeadm init --control-plane-endpoint {{ master_node }} --pod-network-cidr {{ pod_network_cidr }}'
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Create kube directory
  become_user: '{{ service_account }}'
  ansible.builtin.file:
    path: '{{ kube_directory }}'
    state: directory
    mode: u=rwx,g=rwx,o=rx
  become: yes

- name: Copy kubeconfig to home directory
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: '{{ kube_directory }}/config'
    mode: u=rw
  become: yes
