---
# tasks file for master

- name: Intialise master
  ansible.builtin.command:
    cmd: kubeadm init --control-plane-endpoint controlplane --pod-network-cidr 10.32.0.0/12
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: kubeadm_output

- name: Create kube directory
  become_user: ubuntu
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: u=rwx,g=rwx,o=rx
  become: yes

- name: Copy kubeconfig to home directory
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    mode: u=rw
  become: yes
