---
# tasks file for containerd

- name: Add overlay, br_netfilter kernel modules
  community.general.modprobe:
    name: '{{ item }}'
    state: present
    persistent: present
  with_items: '{{ kernel_modules }}'

- name: Set ip forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable IP tables see brdige network
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable IP6 tables see brdige network
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Add packages required for containerd
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items: '{{ containerd_prerequisites }}'

- name: Add apt key rings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Apt signing key on remote server to keyring
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Update permissions of apt docker keyrings to execute
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Get system architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: output
  changed_when: output.rc !=0

- name: Set system architecture fact
  ansible.builtin.set_fact:
    docker_repo: 'deb [arch={{ output.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: Add Docker repository to sources.list.d
  ansible.builtin.copy:
    content: '{{ docker_repo }}'
    dest: /etc/apt/sources.list.d/docker.list
    mode: u=rw,g=r,o=r

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    update_cache: yes
    state: present

- name: Start containerd
  ansible.builtin.systemd:
    name: containerd
    state: started

- name: Update containerd config to default values
  ansible.builtin.shell:
    cmd: containerd config default > /etc/containerd/config.toml
  register: output
  changed_when: output.rc != 0
  notify: Restart containerd

- name: Update Systemd as Cgroup driver
  ansible.builtin.lineinfile:
    line: '            SystemdCgroup = true'
    regexp: '^.*SystemdCgroup.*'
    path: /etc/containerd/config.toml
  notify: Restart containerd
